language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
# goes to the right directory with all the actual files and that
before_install: "cd dashday"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: "nosetests runtests.py"
