language: python
matrix:
  include:
    - python: 3.3
      env: TOXENV=py33
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.5-dev
      env: TOXENV=py35
    - python: nightly
      env: TOXENV=py36
    - python: pypy3
      env: TOXENV=pypy3
  allow_failures:
    - python: 3.5-dev
    - python: nightly
    - python: pypy3
# goes to the right directory with all the actual files and that
before_install: cd dashday
# command to install dependencies
install:
    - pip install -r requirements.txt
    - pip install codecov
# command to run tests
script: nosetests runtests.py --with-coverage
after_success: codecov
